#!/usr/bin/env bash
# Compare code generation, not language runtimes: the same C++ source and
# deterministic random permutation are run under four compiler policies.
set -Eeuo pipefail
[[ $# == 1 && $1 == /home/d3v/random-cpp-compilers-run-* && ! -e $1 ]] || { echo "usage: $0 /home/d3v/random-cpp-compilers-run-UNIQUE" >&2; exit 64; }
run_root=$1; cpu=4; sibling=5; repetitions=15; target_operations=335544320; seed=${RANDOM_CPP_COMPILER_SEED:-20260909}; cases=$(mktemp); trap 'rm -f "$cases"' EXIT
[[ $(cat /sys/devices/system/cpu/cpu$cpu/cpufreq/scaling_governor) == performance && $(cat /sys/devices/system/cpu/cpu$cpu/cpufreq/scaling_min_freq) == $(cat /sys/devices/system/cpu/cpu$cpu/cpufreq/scaling_max_freq) && $(cat /sys/devices/system/cpu/intel_pstate/no_turbo) == 1 && $(cat /proc/sys/kernel/perf_event_paranoid) -le 0 && $(cat /sys/devices/system/cpu/cpu$sibling/online) == 0 ]] || { echo "DUT gate failed" >&2; exit 69; }
declare -A bin=( [gcc13_scalar]=/home/d3v/random-language-run-20260909-v2/bin/random_cpp [gcc13_auto]=/home/d3v/random-compiler-build-20260909/gcc13_auto [clang18_scalar]=/home/d3v/random-compiler-build-20260909/clang18_scalar [clang18_auto]=/home/d3v/random-compiler-build-20260909/clang18_auto )
for compiler in gcc13_scalar gcc13_auto clang18_scalar clang18_auto; do [[ -x ${bin[$compiler]} ]] || { echo "missing $compiler" >&2; exit 66; }; done
mkdir -p "$run_root"/{raw,manifest}; { date --iso-8601=seconds; uname -a; lscpu; grep -H . /sys/devices/system/cpu/cpu$cpu/cpufreq/scaling_{governor,cur_freq,min_freq,max_freq}; cat /sys/devices/system/cpu/intel_pstate/no_turbo; cat /proc/sys/kernel/perf_event_paranoid; g++-13 --version; clang++-18 --version; } > "$run_root/manifest/pre_run_machine.txt" 2>&1
{ sha256sum /home/d3v/random-language-src-20260909/src/random_cpp.cpp /home/d3v/random-language-src-20260909/src/pmu_scope.{c,h}; for compiler in gcc13_scalar gcc13_auto clang18_scalar clang18_auto; do sha256sum "${bin[$compiler]}"; objdump -d -Mintel "${bin[$compiler]}" > "$run_root/manifest/$compiler.disassembly.txt"; done; } > "$run_root/manifest/source_binary_sha256.txt"
printf 'sample_id,round,compiler,footprint_bytes,passes,operations,elapsed_ns,checksum,expected_checksum,pmu_cycles,pmu_instructions,pmu_ref_cycles,pmu_time_enabled,pmu_time_running,pmu_available\n' > "$run_root/raw/samples.csv"; printf 'round,sample_id,compiler,footprint_bytes,passes,shuffle_key\n' > "$run_root/raw/run_order.csv"
for footprint in 32768 36864 262144 1048576 6291456 8388608 536870912; do words=$((footprint/4)); passes=$(((target_operations+words-1)/words)); for compiler in gcc13_scalar gcc13_auto clang18_scalar clang18_auto; do printf '%s,%s,%s\n' "$compiler" "$footprint" "$passes" >> "$cases"; done; done
shuffle_cases(){ local round=$1; awk -F, -v seed="$seed" -v round="$round" 'BEGIN{state=(seed+round*104729)%2147483647}{state=(state*48271)%2147483647;printf "%010d,%s\n",state,$0}' "$cases" | sort -t, -k1,1n; }
for round in $(seq 1 "$repetitions"); do ordinal=0; while IFS=, read -r shuffle_key compiler footprint passes; do ordinal=$((ordinal+1)); sample_id=$(printf 'r%02d-o%02d-%s-%s' "$round" "$ordinal" "$compiler" "$footprint"); printf '%s,%s,%s,%s,%s,%s\n' "$round" "$sample_id" "$compiler" "$footprint" "$passes" "$shuffle_key" >> "$run_root/raw/run_order.csv"; output=$(taskset --cpu-list "$cpu" "${bin[$compiler]}" "$footprint" "$passes"); declare -A f=(); IFS=, read -ra terms <<< "$output"; for term in "${terms[@]}"; do f[${term%%=*}]=${term#*=}; done; for name in bytes passes operations elapsed_ns checksum expected_checksum pmu_cycles pmu_instructions pmu_ref_cycles pmu_time_enabled pmu_time_running pmu_available; do [[ -n ${f[$name]:-} ]] || exit 65; done; [[ ${f[bytes]} == "$footprint" && ${f[passes]} == "$passes" && ${f[elapsed_ns]} -ge 250000000 && ${f[checksum]} == "${f[expected_checksum]}" && ( ${f[pmu_available]} == 1 || ${f[pmu_available]} == true ) && ${f[pmu_time_enabled]} == "${f[pmu_time_running]}" && ${f[pmu_time_enabled]} != 0 ]] || { echo "bad row $sample_id" >&2; exit 65; }; printf '%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n' "$sample_id" "$round" "$compiler" "$footprint" "$passes" "${f[operations]}" "${f[elapsed_ns]}" "${f[checksum]}" "${f[expected_checksum]}" "${f[pmu_cycles]}" "${f[pmu_instructions]}" "${f[pmu_ref_cycles]}" "${f[pmu_time_enabled]}" "${f[pmu_time_running]}" "${f[pmu_available]}" >> "$run_root/raw/samples.csv"; done < <(shuffle_cases "$round"); done
awk -F, 'NR>1 {print $3 "," $4 "," $7/$6 "," $10/$6 "," $11/$6 "," $12/$6}' "$run_root/raw/samples.csv" | sort -t, -k1,1 -k2,2n -k3,3n | awk -F, 'BEGIN{print "compiler,footprint_bytes,repetitions,median_ns_per_load,p10_ns_per_load,p90_ns_per_load,median_cycles_per_load,p10_cycles_per_load,p90_cycles_per_load,median_instructions_per_load,median_ref_cycles_per_load"}function emit(){if(n!=15)exit 65;printf "%s,%s,%d,%.9f,%.9f,%.9f,%.9f,%.9f,%.9f,%.9f,%.9f\n",name,size,n,ns[8],ns[2],ns[14],cy[8],cy[2],cy[14],ins[8],ref[8]}{if(NR==1||$1!=name||$2!=size){if(NR>1)emit();name=$1;size=$2;n=0}ns[++n]=$3;cy[n]=$4;ins[n]=$5;ref[n]=$6}END{emit()}' > "$run_root/raw/summary_random_cpp_compilers.csv"
[[ $(wc -l < "$run_root/raw/summary_random_cpp_compilers.csv") == 29 ]] || exit 65; sha256sum "$run_root/raw"/*.csv "$run_root/manifest"/*.txt > "$run_root/manifest/result_sha256.txt"; echo "completed $run_root"
