//! Rust control for a strict 4-byte random index cycle.
use std::{env,hint::black_box};
#[repr(C)]struct PmuScope{leader_fd:i32,member_fds:[i32;2]}
#[repr(C)]#[derive(Default)]struct PmuResult{cycles:u64,instructions:u64,ref_cycles:u64,time_enabled:u64,time_running:u64}
extern "C"{fn scan_clock_now_ns()->u64;fn scan_pmu_open(p:*mut PmuScope)->i32;fn scan_pmu_start(p:*const PmuScope)->i32;fn scan_pmu_stop(p:*const PmuScope,r:*mut PmuResult)->i32;fn scan_pmu_is_available(p:*const PmuScope)->i32;fn scan_pmu_close(p:*mut PmuScope);}
fn splitmix64(s:&mut u64)->u64{*s=s.wrapping_add(0x9e37_79b9_7f4a_7c15);let mut x=*s;x=(x^(x>>30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);x=(x^(x>>27)).wrapping_mul(0x94d0_49bb_1331_11eb);x^(x>>31)}
fn shuffle(v:&mut[u32]){let mut s=20_260_909u64^0x1223_3445;for i in (1..v.len()).rev(){let j=(splitmix64(&mut s)%(i as u64+1))as usize;v.swap(i,j);}}
#[inline(never)]fn chase(next:&[u32],start:u32,operations:u64)->u32{let mut index=start;for _ in 0..operations{index=next[index as usize];}black_box(index)}
fn main(){let args:Vec<String>=env::args().collect();if args.len()!=3{panic!("usage: index_rust bytes passes")}let bytes:usize=args[1].parse().unwrap();let passes:u64=args[2].parse().unwrap();if bytes<64||bytes%64!=0||passes==0{panic!("bytes must be a nonzero multiple of 64")}let entries=bytes/4;let mut next=vec![0u32;entries];let mut order:Vec<u32>=(0..entries as u32).collect();shuffle(&mut order);for i in 0..entries{next[order[i]as usize]=order[(i+1)%entries];}let start=order[0];let operations=entries as u64*passes;let mut scope=PmuScope{leader_fd:-1,member_fds:[-1,-1]};let mut pmu=PmuResult::default();unsafe{if scan_pmu_open(&mut scope)!=0||scan_pmu_start(&scope)!=0{panic!("could not start PMU")}}let begun=unsafe{scan_clock_now_ns()};let checksum=chase(&next,start,operations);let elapsed=unsafe{scan_clock_now_ns()}-begun;let available=unsafe{if scan_pmu_stop(&scope,&mut pmu)!=0{panic!("could not read PMU")}let a=scan_pmu_is_available(&scope)!=0;scan_pmu_close(&mut scope);a};if checksum!=start||!available||pmu.time_enabled==0||pmu.time_enabled!=pmu.time_running{panic!("invalid checksum or PMU interval")}println!("bytes={bytes},passes={passes},operations={operations},elapsed_ns={elapsed},checksum={checksum},expected_checksum={start},pmu_cycles={},pmu_instructions={},pmu_ref_cycles={},pmu_time_enabled={},pmu_time_running={},pmu_available={}",pmu.cycles,pmu.instructions,pmu.ref_cycles,pmu.time_enabled,pmu.time_running,available as u8);}
